erDiagram
    User ||--o{ UserSession : "Has"
    User ||--o{ UserContact : "Is_User"
    User ||--o{ UserContact : "Is_Contact"
    User ||--o{ UserBlock : "Blocks"
    User ||--o{ UserBlock : "Blocked_By"
    User ||--o{ VerificationCode : "Generates"
    User ||--o{ Message : "Sends"
    User ||--o{ Message : "Receives"
    User ||--o{ Group : "Creates"
    User ||--o{ GroupMember : "Is_Member_Of"
    User ||--o{ GroupMessage : "Sends_Group_Msg"
    Session ||--o{ UserSession : "Contains"
    Group ||--o{ GroupMember : "Has"
    Group ||--o{ GroupMessage : "Contains"

    User {
        id int
        join_date datetime
        photo image
        phone varchar
        full_name varchar
        status varchar
    }

    Session {
        id int
        session_key varchar
        session_data text
        expire_date datetime
    }

    UserSession {
        id int
        user_id int
        session_id int
    }

    UserContact {
        id int
        user_id int
        contact_id int
    }

    UserBlock {
        id int
        user_id int
        blocked_id int
    }

    VerificationCode {
        id int
        user_id int
        code varchar
        expiration_date timestamp
        is_verified bool
    }

    Message {
        id int
        sender_id int
        receiver_id int
        content text
        sent_at datetime
    }

    Group {
        id int
        created_at datetime
        created_by int
        photo image
        name varchar
    }

    GroupMember {
        id int
        user_id int
        group_id int
    }

    GroupMessage {
        id int
        sender_id int
        group_id int
        content text
        sent_at datetime
    }